version: '3'
services:
  redis:
    image: redis:7.0.12
    container_name: redis
    restart: always
    ports:
      - "36379:6379"

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack
    restart: always
    ports:
      - "46379:6379"
