name: crews backend ci

on:
  pull_request:
    branches: [ "dev", "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'crews'
          mysql user: ${{ secrets.TEST_DB_USERNAME }}
          mysql password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Set up Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-port: 36379

      - name: Run Test
        run: ./gradlew clean test
