name: crews backend development version distribute

on:
  push:
    branches: [ "feat/#109-search-with-redisearch" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'crews'
          mysql user: ${{ secrets.TEST_DB_USERNAME }}
          mysql password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Set up Redis And Redis Stack
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose-local.yml"

      - name: Run Test And Create API Documentation
        run: ./gradlew openapi3

      - name: Build with Gradle
        run: ./gradlew bootJar -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_SERVER_IMAGE_NAME }}
          platforms: |
            linux/amd64
            linux/arm64

  alarm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Check if docker-compose-client.yml was modified
        run: |
          git fetch --prune --unshallow
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "docker-compose-client.yml"; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Notify Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "새로운 서버 개발 버전이 배포됐어요!"    
                }
              ],
              "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "도커 컴포즈 파일이 변경됐나요?\n${{ env.modified }}\n<https://github.com/team-crews/crews-server-spring/blob/dev/docker-compose-local.yml|바로가기>"
                    }
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
